// ============================================================================
// NestJS Backend Blueprint & Architecture Guide
// Este arquivo documenta a estrutura exata recomendada para o seu backend NestJS
// ============================================================================

export interface NestEndpointDef {
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  path: string;
  summary: string;
  requestDto?: string;
  responseDto: string;
  authRequired: boolean;
  permission?: string;
  description: string;
  sampleBody?: any;
  sampleResponse?: any;
}

export interface NestModuleDef {
  name: string;
  folder: string;
  description: string;
  controller: string;
  service: string;
  entities: string[];
  endpoints: NestEndpointDef[];
}

export const NESTJS_MODULES_BLUEPRINT: NestModuleDef[] = [
  {
    name: 'AuthModule',
    folder: 'src/modules/auth',
    description: 'Autenticação JWT, login, refresh token e recuperação de perfil.',
    controller: 'AuthController (@Controller("auth"))',
    service: 'AuthService',
    entities: ['User', 'RefreshToken'],
    endpoints: [
      {
        method: 'POST',
        path: '/api/auth/login',
        summary: 'Autenticar com email e senha',
        requestDto: 'LoginDto',
        responseDto: 'AuthResponseDto',
        authRequired: false,
        description: 'Valida credenciais com hash seguro e retorna accessToken JWT.',
        sampleBody: { email: 'admin@silkprint.com.br', password: 'sua_senha_aqui' },
        sampleResponse: {
          accessToken: 'eyJhbGciOiJIUzI1NiIsIn...',
          tokenType: 'Bearer',
          expiresIn: 86400,
          user: { id: 'usr_123', name: 'Admin Master', email: 'admin@silkprint.com.br', jobTitle: 'Diretor', department: 'Diretoria' },
        },
      },
      {
        method: 'GET',
        path: '/api/auth/me',
        summary: 'Obter dados do usuário autenticado',
        responseDto: 'AuthUserResponseDto',
        authRequired: true,
        description: 'Lê o payload do token JWT e retorna o perfil com permissões consolidadas.',
      },
      {
        method: 'POST',
        path: '/api/auth/change-password',
        summary: 'Alterar senha do usuário logado',
        requestDto: 'ChangePasswordDto',
        responseDto: '{ success: boolean, message: string }',
        authRequired: true,
        description: 'Verifica a senha atual e grava a nova senha criptografada.',
      },
    ],
  },
  {
    name: 'UsersModule',
    folder: 'src/modules/users',
    description: 'Gestão de colaboradores, perfis vinculados e permissões avulsas.',
    controller: 'UsersController (@Controller("users"))',
    service: 'UsersService',
    entities: ['User', 'UserPermission'],
    endpoints: [
      {
        method: 'GET',
        path: '/api/users',
        summary: 'Listar todos os colaboradores/usuários',
        responseDto: 'UserResponseDto[]',
        authRequired: true,
        permission: 'users.view',
        description: 'Retorna a lista de usuários com filtros opcionais de busca, departamento e status.',
      },
      {
        method: 'GET',
        path: '/api/users/:id',
        summary: 'Buscar usuário por ID',
        responseDto: 'UserResponseDto',
        authRequired: true,
        permission: 'users.view',
        description: 'Retorna detalhes completos do colaborador com permissões calculadas.',
      },
      {
        method: 'POST',
        path: '/api/users',
        summary: 'Criar novo usuário/colaborador',
        requestDto: 'CreateUserDto',
        responseDto: 'UserResponseDto',
        authRequired: true,
        permission: 'users.create',
        description: 'Cadastra colaborador com hash de senha e associa aos perfis de acesso.',
        sampleBody: {
          name: 'Carlos Oliveira',
          email: 'carlos@silkprint.com.br',
          password: 'senhaSegura123',
          whatsapp: '51999998888',
          jobTitle: 'Arte-Finalista',
          department: 'Arte & Pré-Impressão',
          status: 'Ativo',
          profileIds: ['prof_arte'],
        },
      },
      {
        method: 'PUT',
        path: '/api/users/:id',
        summary: 'Atualizar dados do usuário',
        requestDto: 'UpdateUserDto',
        responseDto: 'UserResponseDto',
        authRequired: true,
        permission: 'users.edit',
        description: 'Atualiza informações cadastrais e cargos do colaborador.',
      },
      {
        method: 'DELETE',
        path: '/api/users/:id',
        summary: 'Remover usuário',
        responseDto: '{ success: boolean }',
        authRequired: true,
        permission: 'users.delete',
        description: 'Exclui ou desativa permanentemente o colaborador.',
      },
    ],
  },
  {
    name: 'ProfilesModule',
    folder: 'src/modules/profiles',
    description: 'Gestão de Perfis de Acesso e Matriz de Permissões RBAC.',
    controller: 'ProfilesController (@Controller("profiles"))',
    service: 'ProfilesService',
    entities: ['AccessProfile', 'PermissionDefinition'],
    endpoints: [
      {
        method: 'GET',
        path: '/api/profiles',
        summary: 'Listar perfis de acesso',
        responseDto: 'ProfileResponseDto[]',
        authRequired: true,
        permission: 'profiles.view',
        description: 'Retorna todos os perfis com suas permissões (resource.action), telas e rotinas liberadas.',
      },
      {
        method: 'POST',
        path: '/api/profiles',
        summary: 'Criar novo perfil de acesso',
        requestDto: 'CreateProfileDto',
        responseDto: 'ProfileResponseDto',
        authRequired: true,
        permission: 'profiles.create',
        description: 'Cria perfil com array de permissões granular.',
      },
      {
        method: 'PUT',
        path: '/api/profiles/:id',
        summary: 'Atualizar perfil de acesso',
        requestDto: 'UpdateProfileDto',
        responseDto: 'ProfileResponseDto',
        authRequired: true,
        permission: 'profiles.edit',
        description: 'Altera o escopo de permissões de um perfil existente.',
      },
    ],
  },
  {
    name: 'ClientsModule',
    folder: 'src/modules/clients',
    description: 'CRM, cadastro de clientes, endereços e histórico de compras.',
    controller: 'ClientsController (@Controller("clientes"))',
    service: 'ClientsService',
    entities: ['Client'],
    endpoints: [
      {
        method: 'GET',
        path: '/api/clientes',
        summary: 'Listar clientes com busca e paginação',
        responseDto: 'ClientResponseDto[]',
        authRequired: true,
        permission: 'customers.view',
        description: 'Retorna a lista de clientes com contador de pedidos e valor total gasto.',
      },
      {
        method: 'POST',
        path: '/api/clientes',
        summary: 'Cadastrar novo cliente',
        requestDto: 'CreateClientDto',
        responseDto: 'ClientResponseDto',
        authRequired: true,
        permission: 'customers.create',
        description: 'Salva cliente e normaliza número do WhatsApp e endereço.',
        sampleBody: {
          name: 'Agência Criativa Alpha',
          whatsapp: '51988776655',
          email: 'contato@alphacriativa.com.br',
          cpfCnpj: '12.345.678/0001-90',
          cidade: 'Porto Alegre',
          estado: 'RS',
        },
      },
      {
        method: 'PUT',
        path: '/api/clientes/:id',
        summary: 'Atualizar dados do cliente',
        requestDto: 'UpdateClientDto',
        responseDto: 'ClientResponseDto',
        authRequired: true,
        permission: 'customers.edit',
        description: 'Atualiza dados cadastrais.',
      },
      {
        method: 'DELETE',
        path: '/api/clientes/:id',
        summary: 'Excluir cliente',
        responseDto: '{ success: boolean }',
        authRequired: true,
        permission: 'customers.delete',
        description: 'Remove o cliente do sistema se não houver pedidos vinculados.',
      },
    ],
  },
  {
    name: 'ProductsModule',
    folder: 'src/modules/products',
    description: 'Catálogo de produtos gráficos, precificação por m², quantidade e tabelas escalonadas.',
    controller: 'ProductsController (@Controller("produtos"))',
    service: 'ProductsService',
    entities: ['Product', 'PriceTier'],
    endpoints: [
      {
        method: 'GET',
        path: '/api/produtos',
        summary: 'Listar produtos cadastrados',
        responseDto: 'ProductResponseDto[]',
        authRequired: true,
        permission: 'products.view',
        description: 'Retorna produtos do catálogo com faixas de preço e acabamentos compatíveis.',
      },
      {
        method: 'POST',
        path: '/api/produtos',
        summary: 'Criar produto no catálogo',
        requestDto: 'CreateProductDto',
        responseDto: 'ProductResponseDto',
        authRequired: true,
        permission: 'products.create',
        description: 'Cria produto com suporte a preço fixo, m² ou faixas de quantidade.',
        sampleBody: {
          name: 'Banner Lona Frontlight 440g',
          category: 'Comunicação Visual',
          price: 65.0,
          cost: 28.0,
          unit: 'm²',
          isM2: true,
          baseM2Price: 65.0,
          productionTime: '2 dias úteis',
          isActive: true,
        },
      },
      {
        method: 'PUT',
        path: '/api/produtos/:id',
        summary: 'Atualizar produto',
        requestDto: 'UpdateProductDto',
        responseDto: 'ProductResponseDto',
        authRequired: true,
        permission: 'products.edit',
        description: 'Altera especificações técnicas e preços do produto.',
      },
    ],
  },
  {
    name: 'FinishingsModule',
    folder: 'src/modules/finishings',
    description: 'Acabamentos gráficos (Ilhós, Verniz UV, Dobra, Vinco, Laminação).',
    controller: 'FinishingsController (@Controller("acabamentos"))',
    service: 'FinishingsService',
    entities: ['Finishing'],
    endpoints: [
      {
        method: 'GET',
        path: '/api/acabamentos',
        summary: 'Listar acabamentos disponíveis',
        responseDto: 'FinishingResponseDto[]',
        authRequired: true,
        permission: 'finishings.view',
        description: 'Retorna a tabela de acabamentos e regras de cobrança.',
      },
      {
        method: 'POST',
        path: '/api/acabamentos',
        summary: 'Cadastrar acabamento',
        requestDto: 'CreateFinishingDto',
        responseDto: 'FinishingResponseDto',
        authRequired: true,
        permission: 'finishings.create',
        description: 'Adiciona novo acabamento com tipo de cobrança (unidade, m² ou fixo).',
      },
    ],
  },
  {
    name: 'QuotesModule',
    folder: 'src/modules/quotes',
    description: 'Motor de cálculo de orçamentos, propostas comerciais e conversão em OS.',
    controller: 'QuotesController (@Controller("orcamentos"))',
    service: 'QuotesService',
    entities: ['Quote', 'QuoteItem'],
    endpoints: [
      {
        method: 'GET',
        path: '/api/orcamentos',
        summary: 'Listar orçamentos gerados',
        responseDto: 'QuoteResponseDto[]',
        authRequired: true,
        permission: 'quotes.view',
        description: 'Lista propostas com status (rascunho, enviado, aprovado, convertido).',
      },
      {
        method: 'POST',
        path: '/api/orcamentos',
        summary: 'Criar proposta comercial / orçamento',
        requestDto: 'CreateQuoteDto',
        responseDto: 'QuoteResponseDto',
        authRequired: true,
        permission: 'quotes.create',
        description: 'Calcula itens, acabamentos, dimensões e gera PDF ou link para o cliente.',
      },
      {
        method: 'POST',
        path: '/api/orcamentos/:id/convert',
        summary: 'Converter Orçamento em Pedido de Produção',
        requestDto: 'ConvertQuoteToOrderDto',
        responseDto: 'OrderResponseDto',
        authRequired: true,
        permission: 'quotes.convert',
        description: 'Cria uma Ordem de Serviço na esteira de produção e marca o orçamento como convertido.',
      },
    ],
  },
  {
    name: 'OrdersModule',
    folder: 'src/modules/orders',
    description: 'Gestão de Pedidos, Kanban de Produção e Rastreio.',
    controller: 'OrdersController (@Controller("pedidos"))',
    service: 'OrdersService',
    entities: ['Order', 'OrderItem', 'OrderMessage'],
    endpoints: [
      {
        method: 'GET',
        path: '/api/pedidos',
        summary: 'Listar pedidos / Ordens de Produção',
        responseDto: 'OrderResponseDto[]',
        authRequired: true,
        permission: 'orders.view',
        description: 'Retorna a fila de pedidos com status de produção e pagamento.',
      },
      {
        method: 'POST',
        path: '/api/pedidos',
        summary: 'Criar novo pedido',
        requestDto: 'CreateOrderDto',
        responseDto: 'OrderResponseDto',
        authRequired: true,
        permission: 'orders.create',
        description: 'Gera código de rastreio OS-# e adiciona à esteira de produção.',
      },
      {
        method: 'PUT',
        path: '/api/pedidos/:id/status',
        summary: 'Avançar status na esteira de produção',
        requestDto: 'UpdateOrderStatusDto',
        responseDto: 'OrderResponseDto',
        authRequired: true,
        permission: 'orders.update_status',
        description: 'Atualiza o status (Ex: criando_arte -> em_producao -> aguardando_retirada) e dispara webhook.',
      },
      {
        method: 'PUT',
        path: '/api/pedidos/:id/pagamento',
        summary: 'Atualizar status de pagamento',
        requestDto: 'UpdateOrderPaymentDto',
        responseDto: 'OrderResponseDto',
        authRequired: true,
        permission: 'orders.update_payment',
        description: 'Atualiza valor pago e lança transação de receita no financeiro.',
      },
      {
        method: 'POST',
        path: '/api/pedidos/:id/mensagens',
        summary: 'Adicionar mensagem no chat/histórico do pedido',
        requestDto: 'AddOrderMessageDto',
        responseDto: 'OrderResponseDto',
        authRequired: true,
        permission: 'orders.edit',
        description: 'Registra interação de atendimento com o cliente no pedido.',
      },
    ],
  },
  {
    name: 'FinancialModule',
    folder: 'src/modules/financial',
    description: 'Fluxo de Caixa, Contas a Pagar/Receber, DRE e Conciliação.',
    controller: 'FinancialController (@Controller("transacoes"))',
    service: 'FinancialService',
    entities: ['Transaction'],
    endpoints: [
      {
        method: 'GET',
        path: '/api/transacoes',
        summary: 'Listar lançamentos financeiros',
        responseDto: 'TransactionResponseDto[]',
        authRequired: true,
        permission: 'financial.view',
        description: 'Retorna receitas e despesas com filtros de vencimento, status e categoria.',
      },
      {
        method: 'POST',
        path: '/api/transacoes',
        summary: 'Lançar receita ou despesa manual',
        requestDto: 'CreateTransactionDto',
        responseDto: 'TransactionResponseDto',
        authRequired: true,
        permission: 'financial.create',
        description: 'Cria entrada de caixa ou conta a pagar.',
      },
      {
        method: 'GET',
        path: '/api/transacoes/summary/overview',
        summary: 'Resumo financeiro e projeção de saldo',
        responseDto: 'FinancialSummaryDto',
        authRequired: true,
        permission: 'financial.view',
        description: 'Total de receitas, despesas, saldo atual e valores pendentes.',
      },
      {
        method: 'GET',
        path: '/api/transacoes/reports/dre',
        summary: 'Demonstrativo de Resultados do Exercício (DRE)',
        responseDto: 'DREResponseDto',
        authRequired: true,
        permission: 'financial.report',
        description: 'Calcula receita bruta, deduções, custos operacionais e margem de lucro líquido.',
      },
    ],
  },
  {
    name: 'StorageModule',
    folder: 'src/modules/storage',
    description: 'Gestão de arquivos, upload de artes gráficas e comprovantes via S3 / MinIO.',
    controller: 'StorageController (@Controller("storage"))',
    service: 'StorageService',
    entities: ['FileRecord'],
    endpoints: [
      {
        method: 'POST',
        path: '/api/storage/upload',
        summary: 'Upload de arquivo (Multipart / FormData)',
        responseDto: 'FileResponseDto',
        authRequired: true,
        permission: 'files.upload',
        description: 'Recebe arquivo (PDF, CDR, AI, JPG, PNG) e armazena no bucket S3.',
      },
      {
        method: 'GET',
        path: '/api/storage/files',
        summary: 'Listar arquivos salvos',
        responseDto: 'FileResponseDto[]',
        authRequired: true,
        permission: 'files.view',
        description: 'Retorna arquivos filtrados por categoria ou pedido.',
      },
    ],
  },
  {
    name: 'IntegrationsModule',
    folder: 'src/modules/integrations',
    description: 'Disparos via WhatsApp (Evolution API) e Webhooks automáticos (n8n).',
    controller: 'IntegrationsController (@Controller("integrations"))',
    service: 'IntegrationsService',
    entities: ['WebhookLog'],
    endpoints: [
      {
        method: 'GET',
        path: '/api/integrations/whatsapp/status',
        summary: 'Verificar status da conexão do WhatsApp',
        responseDto: 'WhatsAppStatusResponseDto',
        authRequired: true,
        permission: 'integrations.view',
        description: 'Checa se a instância da Evolution API está conectada.',
      },
      {
        method: 'POST',
        path: '/api/integrations/whatsapp/send',
        summary: 'Enviar mensagem direta no WhatsApp',
        requestDto: 'SendWhatsAppMessageDto',
        responseDto: '{ success: boolean }',
        authRequired: true,
        permission: 'integrations.whatsapp_send',
        description: 'Dispara notificação de status ou comprovante para o cliente.',
      },
      {
        method: 'POST',
        path: '/api/integrations/n8n/trigger',
        summary: 'Disparar webhook customizado para o n8n',
        requestDto: 'N8nWebhookTriggerDto',
        responseDto: '{ success: boolean }',
        authRequired: true,
        permission: 'integrations.n8n_trigger',
        description: 'Envia evento para fluxo de automação.',
      },
    ],
  },
];
